### ISSUE TITLE
Authentication: Forget Password-UI

### ISSUE THREAD

**Issue by dabsclement** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#10]
- Develop the forget password page UI appropriately
- Ensure they are responsive and follow the responsive design on the Figma
- Implement images properly
- Follow the colour guide and the appropriate colours

**Comment by yes-im-harsh** [comment]
I would like to work on this. Please Assign it to me

**Comment by dprincecoder** [comment]
@yes-im-harsh are you still working on this?
