### ISSUE TITLE
User Dashboard: Wishlist - Select and Delete Products on Wishlist

### ISSUE THREAD

**Issue by nhorah** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#112]
This screen allows users to select and delete products added to their wishlist.
- Design a screen that allows users select and delete items from their wishlist
- The selected item should easily be noticed from unselected products.
- Design a confirmation pop up that allows users to confirm if they really want to delete those products
- Design a simple alert that informs the user that the product has been successfully deleted from their wishlist
- Design must be fully responsive (desktop, tablet and mobile views must be created).
- Ensure you use the colors and typography on the style guide to ensure consistency.

**Comment by nhorah** [comment]
hey @Cisco-A this is a design issue, not development😢😢

**Comment by Cisco-A** [comment]
@nhorah but the design that fits the description is already on the Figma page and that's what I developed... Did I just waste my time?🙂💔

**Comment by nhorah** [comment]
@Cisco-A no you didn't😂😂

All the designs are ready but designers haven't added their contributions to GitHub
We are just adding the contributions

**Comment by Cisco-A** [comment]
@nhorah oh okay... So what's the label for issues we're to develop? Or there isn't any yet?

**Comment by nhorah** [comment]
@Cisco-A just check through but "design" labels are for design issues
Well done

**Comment by Cisco-A** [comment]
@nhorah alright, thanks.
