### ISSUE TITLE
Replacement of old brand logo with the correct brand logo

### ISSUE THREAD

**Issue by De-mi-de** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#125]
Replacement of logo with the correct brand logo on the landing page across all screens (mobile, iPad and desktop screen).

**Comment by Developer-in-Tech** [comment]
@Hussain6 will assign to you

**Comment by sowmiya-venkatesan** [comment]
Hi @De-mi-de Could you please assign me this? I'll complete it ASAP
