### ISSUE TITLE
Authentication: Reset-password-Success-UI

### ISSUE THREAD

**Issue by dabsclement** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#13]
- Develop the reset password success page UI appropriately
- Ensure they are responsive and follow the responsive design on the Figma
- Implement images properly
- Follow the colour guide and the appropriate colours

**Comment by mnamesujit** [comment]
Hey can i work with you please assign me this issue

**Comment by dprincecoder** [comment]
@mnamesujit progress check on this issue?

**Comment by Osilaja78** [comment]
On it
