### ISSUE TITLE
Design of 404 Error Page for Landing Page

### ISSUE THREAD

**Issue by nhorah** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#134]
There is no error page that indicates when a user has taken a wrong action or when a user's internet connection is not strong enough to load a page.

**Comment by Anuran12** [comment]
Hi @nhorah i would like to work on this

**Comment by nhorah** [comment]
Hi @Anuran12, we are just creating the issues now but someone has worked on it, sorry

**Comment by Anuran12** [comment]
@nhorah ohh okay. Can I work another on issue ?
