### ISSUE TITLE
Addition of Side Navigation for User Dashboard - Mobile 

### ISSUE THREAD

**Issue by nhorah** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#139]
There is no side navigation for the mobile view of the users' dashboard

**Comment by syprogrammer** [comment]
can you assign me

**Comment by nhorah** [comment]
Hi @syprogrammer we are just creating the issue but someone has worked on it already
sorry

**Comment by syprogrammer** [comment]
ok
