### ISSUE TITLE
Animations feature request

### ISSUE THREAD

**Issue by MarsIncarnate** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#149]

**Comment by JohnChizzy** [comment]
Is this issue still open? Can I work it??

**Comment by dprincecoder** [comment]
@MarsIncarnate are you working on this still yet ?

**Comment by MarsIncarnate** [comment]
I'm now staying in an area with good electricity. I'll close this issue soon.

**Comment by dprincecoder** [comment]
@MarsIncarnate  make a pull request soon

**Comment by MarsIncarnate** [comment]
I'm on it.
