### ISSUE TITLE
Buttons behaviour

### ISSUE THREAD

**Issue by MarsIncarnate** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#150]

**Comment by MarsIncarnate** [comment]
Is it alright to assign this to myself?

**Comment by UditNS** [comment]
Hi @MarsIncarnate, I want to work on this.

**Comment by DanielUdechukwu** [comment]
Hi @MarsIncarnate. I'd like to work on this if possible

**Comment by dprincecoder** [comment]
@MarsIncarnate what level is this issue ?

**Comment by MarsIncarnate** [comment]
I'm already done with it all that's left is to create a pull request.

**Comment by dprincecoder** [comment]
@MarsIncarnate is this issue fixed?

**Comment by MarsIncarnate** [comment]
Yeah it is. I'm surprised it isn't closed, I tagged it in my PR. I'll close it

**Comment by MarsIncarnate** [comment]
Closed by #312
