### ISSUE TITLE
Add scroll to top button/link

### ISSUE THREAD

**Issue by MarsIncarnate** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#153]
### add a scroll to top button that swiftly brings the user to the top of the page

**Comment by dprincecoder** [comment]
@MarsIncarnate are you still working on this ?

**Comment by MarsIncarnate** [comment]
@dprincecoder It appears this issue has been resolved, the one who resolved it however failed to tag this issue so it would be closed.
