### ISSUE TITLE
Feature- sliding customer review section 

### ISSUE THREAD

**Issue by MarsIncarnate** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#154]

**Comment by ThisisMS11** [comment]
Can you assign me this one?

**Comment by Blessing-Tolani** [comment]
@MarsIncarnate can I pick this up

**Comment by MarsIncarnate** [comment]
Yeah. You can

**Comment by Blessing-Tolani** [comment]
@MarsIncarnate Done, thank you

**Comment by Blessing-Tolani** [comment]
@ThisisMS11 I have unassigned my self, Please you can pick it up

**Comment by MarsIncarnate** [comment]
@ThisisMS11 you can pick it up if you've got experience with swiperjs.

**Comment by ThisisMS11** [comment]
@MarsIncarnate  Thanks i will do it.
