### ISSUE TITLE
Admin: Dashboard

### ISSUE THREAD

**Issue by ingressive4good** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#166]
Title
Develop the Admin Dashboard Pages

## Summary

- Develop the  11 pages
- This issue is for an experience developer that really understand how to interpret and develop the designs

## Additional information

- Send a pull request for each of the pages
- Ensure you look through the code base for usable components to avoid duplicates.
- Check the user dashboard components for some useable component
- Follow the existing file structure
- This issue is dependent on issue #163 ensure the issue is closed first to make your work easier

**Comment by Osilaja78** [comment]
Okay, i would like to work on this issue, seems it's been there for a while and no experienced developer is willing to take it up. I would try to implement the design as best as i can. The only one thing i'm still trying to figure out is how to implement the graph, i know i'll get it. @ingressive4good @t-bello7 @dprincecoder i don't just want to assign myself, need to know if it's okay for me to work on it. Please i'll be awaiting your reply on this.

**Comment by dprincecoder** [comment]
@Osilaja78 make sure any of the pages, have not been developed by another person, and also check out for open and closed PRs that may have done this before you start working.

**Comment by Osilaja78** [comment]
Alright will do just that.

**Comment by Osilaja78** [comment]
There are some drop-down contents missing in the admin dashboard page, already made comments on them, o don't know if I'm saying this in the right place. @t-bello7 @dprincecoder

**Comment by dprincecoder** [comment]
If the content are in the figma design then you can create an issue to tackle and fix it

**Comment by Osilaja78** [comment]
It's not in the figma design, that's what I was trying to say. The design shows there's a drop-down but I can't find it's contents on the figma board @dprincecoder

**Comment by dprincecoder** [comment]
Alright you can mention this in the chat forum
