### ISSUE TITLE
Admin: Develop the product pages

### ISSUE THREAD

**Issue by t-bello7** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#167]
## Title
Develop the pages related to viewing, editing, deleting, and uploading products.

## Summary
- Build mobile responsive table components based on the design. Ensure to add this component to the molecule folder so it can be reused in other pages having tables

## Additional information
- The pull request to close this issue should follow the file structure.

**Comment by Blessing-Tolani** [comment]
@t-bello7 do I have to wait for the admin layout template to be ready

**Comment by t-bello7** [comment]
Yes @Blessing-Tolani .It will be ready before tomorrow morning. You can keep working on the component and just plug it in when the layout is ready.

**Comment by Blessing-Tolani** [comment]
@t-bello7 Okay

**Comment by ingressive4good** [comment]
@Blessing-Tolani the layout is ready you can proceed with your work

**Comment by Blessing-Tolani** [comment]
Yes, I am on it

**Comment by Blessing-Tolani** [comment]
@t-bello7 should I the different features like upload, view, edit products in different branch so atleast I can show progress or do everything inside one branch

**Comment by t-bello7** [comment]
You can do it one branch
