### ISSUE TITLE
User-Dashboard: Messages

### ISSUE THREAD

**Issue by dabsclement** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#17]
- Develop the pages of the User-Dashboard message UI appropriately
- The user dashboard message contains 2 pages ( you should send a pull request for each of the pages)
- Ensure they are responsive and follow the responsive design on the Figma
- Implement images properly
- Follow the colour guide and the appropriate colours

**Comment by omotayomialake** [comment]
Hi, i will like to take on this task please

**Comment by omotayomialake** [comment]
Hi, i will like to take on this task please

**Comment by zakariyahrobiat** [comment]
hi please assign me to this issue. I will like to work on it

**Comment by Sandee004** [comment]
@ingressive4good 
I'd like to take this

**Comment by ingressive4good** [comment]
@Sandee004 What's in the progress status on this?

**Comment by omotayomialake** [comment]
I actually requested for this first

**Comment by omotayomialake** [comment]
@dabsclement can i still get assigned?

**Comment by omotayomialake** [comment]
@d-a-ve

**Comment by ingressive4good** [comment]
@omotayomialake wait till the end of the day, if @Sandee004 doesn't comment then you can assign the task to yourself

**Comment by omotayomialake** [comment]
@ingressive4good it seem i haven’t been added to this repository, i can’t seem to assign myself to it, that was why i commented instead

**Comment by ingressive4good** [comment]
Invite sent

**Comment by Sandee004** [comment]
I didn't get an invite too that's why I didn't assign myself

**Comment by d-a-ve** [comment]
@omotayomialake sorry, my bad. I thought you were the person that removed the first assignment I didn't take a good look at the username.

Like @dabsclement said, if @Sandee004 hasn't replied by day's end you can assign yourself.

I will do my best to remove his assignment if he hasn't replied.

**Comment by d-a-ve** [comment]
@Sandee004 just tag @ingressive4good to send you an invite.

**Comment by Sandee004** [comment]
@ingressive4good I didn't get an invite 🤲

**Comment by Osilaja78** [comment]
I think this issue has a PR already, why is it not closed.

**Comment by dprincecoder** [comment]
this is done
