### ISSUE TITLE
Admin: User-Create Sub-Admin

### ISSUE THREAD

**Issue by ingressive4good** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#172]
##Title
Develop the Admin Create Sub-Admin Pages

## Summary

- This Task contain 5 pages
- Develop the 5 pages

## Additional information

- Send a pull request for each of the pages
- Ensure you look through the code base for usable components to avoid duplicates.
-So of the modals on the pages already exist as components, ensure you check them
- Follow the existing file structure

**Comment by JohnChizzy** [comment]
I would like to work on this pls!

**Comment by Osilaja78** [comment]
Hi @ingressive4good ,i think there are actually two pages to be developed,  the remaining three pages are success and error popups which will be handled using state hooks. I hope that's fine.
