### ISSUE TITLE
Admin: Users, User-Profile

### ISSUE THREAD

**Issue by ingressive4good** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#173]
##Title
Develop the Admin Users, User Pages

## Summary

- This Task contain 2 pages
- Develop the 2 pages

## Additional information

- Send a pull request for each of the pages
- Ensure you look through the code base for usable components to avoid duplicates.
- Follow the existing file structure

**Comment by yhoungdev** [comment]
i can work on this.
Do you have a UI design ready for it ? or i should design from my imaginations

**Comment by ingressive4good** [comment]
@yhoungdev check the ReadMe file you will see the UI design

**Comment by ingressive4good** [comment]
@Mudi-Igbinoba are you working on this now?

**Comment by Mudi-Igbinoba** [comment]
@ingressive4good Yes I am
