### ISSUE TITLE
Admin: Develop the Admin Suspend Account popup

### ISSUE THREAD

**Issue by t-bello7** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#174]
## Title 
Develop the Admin Suspend Account popup

## Summary 
- Develop the admin suspend account popup.

## Additional Information
- Kindly ensure to reuse the popup components created in the molecules folder.

**Comment by rahul-s-bhatt** [comment]
Hi @t-bello7 , I'd like to contribute to this issue. I have a question as regarding where would I have to place my popup as I m unable to find the code related to admin side.

**Comment by t-bello7** [comment]
@rahul-s-bhatt  This issue depends on issue #175 which is yet to be done. You can create the component and its states that whoever works on #175 use the component.
 
![Screenshot from 2022-10-15 08-11-29](https://user-images.githubusercontent.com/24270269/195974285-a8409951-0087-413f-8643-384b672cea32.png)
