### ISSUE TITLE
User-Dashboard: Products (View uploaded products)

### ISSUE THREAD

**Issue by dabsclement** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#18]
- Develop the User Dashboard view uploaded product pages UI appropriately
- The user dashboard upload product page contains 4 pages ( you should send a pull request for each of the pages)
- Ensure they are responsive and follow the responsive design on the Figma
- Implement images properly
- Follow the colour guide and the appropriate colours

**Comment by cisnejo** [comment]
I'd like to implement this! If you could assign and point me to the figma design that'd be great!

**Comment by dabsclement** [comment]
it has been assigned to you @cisnejo check the readme and contribute.md file

**Comment by cisnejo** [comment]
Sorry about that. I thought it was still open for assignment. Feel free to un-assign me.
