### ISSUE TITLE
Design of 404 Error Page for User Dashboard

### ISSUE THREAD

**Issue by nhorah** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#188]
There is no error page that indicates when a user has taken a wrong action or when a user's internet connection is not strong enough to load a page.

**Comment by yhoungdev** [comment]
Can you assign this to me ?

**Comment by manan18** [comment]
please assign me this issue

**Comment by ingressive4good** [comment]
it's a design issue, not development
