### ISSUE TITLE
Navbar, Hero and Section Component of Landing Page

### ISSUE THREAD

**Issue by ingressive4good** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#2]
- Develop the home page UI appropriately
- Ensure they are responsive and follow the responsive design on the figma
- Implement images properly
- Follow the color guide and the appropriate colors

**Comment by riyaku11** [comment]
I would like to work on this, please assign this to me

**Comment by ScottDeev** [comment]
Is this for the landing page?

**Comment by thisletterk** [comment]
@ScottDeev , yes

**Comment by LazyCoder4542** [comment]
i want in on this, please assign

**Comment by msboffl** [comment]
Can you please assign this to me, i will work

**Comment by ingressive4good** [comment]
Alright @CyberGeni looking forward to your pull request

**Comment by CyberGeni** [comment]
i need some config (fonts) from #34 to complete my project. can i assign myself that issue and open a pull request so i can continue with this?

i've solved the issue already, just to open a PR

**Comment by ingressive4good** [comment]
Yes, assign the issue to yourself

**Comment by msboffl** [comment]
Can you please break this into subproblems like components - navbar, main, footer

**Comment by t-bello7** [comment]
I agree with @msboffl. Breaking down a page into components would allow more developers to contribute.
