### ISSUE TITLE
User-Dashboard: Products (Delete uploaded products)

### ISSUE THREAD

**Issue by dabsclement** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#20]
- Develop the User Dashboard delete uploaded product pages UI appropriately
- The user dashboard upload product page contains 4 pages ( you should send a pull request for each of the pages)
- Ensure they are responsive and follow the responsive design on the Figma
- Implement images properly
- Follow the colour guide and the appropriate colours

**Comment by zakariyahrobiat** [comment]
Hi, please assign me to this. I would love to work on this

**Comment by ingressive4good** [comment]
hello @zakariyahrobiat you haven't sent a pull request to close this issue? what is the progress status

**Comment by dprincecoder** [comment]
@zakariyahrobiat whats the status on this, if you have made a PR try and link this issue

**Comment by zakariyahrobiat** [comment]
@dprincecoder done
