### ISSUE TITLE
User-Dashboard: Wishlist(View product on wishlist)

### ISSUE THREAD

**Issue by dabsclement** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#21]
- Develop the User Dashboard wishlist pages UI appropriately
- The user dashboard upload product page contains 3 pages ( you should send a pull request for each of the pages)
- Ensure they are responsive and follow the responsive design on the Figma
- Implement images properly
- Follow the colour guide and the appropriate colours

**Comment by Osilaja78** [comment]
Hi, I would like to work on this if you would assign it to me.

**Comment by ingressive4good** [comment]
Assigned, looking forward to your pull request @Osilaja78

**Comment by ingressive4good** [comment]
@Osilaja78 what is the status of this issue you haven't sent any pull request

**Comment by Osilaja78** [comment]
I'm very sorry for the delay @ingressive4good , I quickly went through tailwind CSS since I've never worked with it. Working on it already, will get a PR soon.

**Comment by ingressive4good** [comment]
Alight, looking forward to it
