### ISSUE TITLE
User-Dashboard: Wishlist(Select & Delete product on wishlist)

### ISSUE THREAD

**Issue by dabsclement** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#22]
Develop the User Dashboard wishlist pages UI appropriately
The user dashboard upload product page contains 2 pages ( you should send a pull request for each of the pages)
Ensure they are responsive and follow the responsive design on the Figma
Implement images properly
Follow the colour guide and the appropriate colours

**Comment by Cisco-A** [comment]
Good day @ingressive4good, I am done with styling the atom components and presently working on the molecule components. I should be able to get to the template and pages component on or before Saturday.

**Comment by ingressive4good** [comment]
Alright

**Comment by Osilaja78** [comment]
Hi @ingressive4good is this issue closed?

**Comment by Cisco-A** [comment]
This issue should be related to pull request #146 and has been closed as completed.
