### ISSUE TITLE
User-Dashboard: Help and Support

### ISSUE THREAD

**Issue by dabsclement** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#25]
Develop the User Dashboard help and support page UI appropriately
Ensure they are responsive and follow the responsive design on the Figma
Implement images properly
Follow the colour guide and the appropriate colours

**Comment by msboffl** [comment]
Hi, @dabsclement @Shegun-istaken Can you please assign this to me, i will work
