### ISSUE TITLE
Admin Design - Profile (Desktop View)

### ISSUE THREAD

**Issue by De-mi-de** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#270]
Design the desktop view for the admin profile page.

The product upload screen will comprise of;
- A section containing admin's name, display picture and stars to indicate that the profile belongs to the admin.

- A section for admin's personal information, comprising of;
      - Input field for admin's name, email, phone number and location.

- A section for password
      - Input field for new password and confirm password
  
- A "Cancel and Save Changes button"

Ensure you use colors and typography on the style guide to ensure consistency.

**Comment by harsh0620** [comment]
Hi @De-mi-de Please assign me this task.
