### ISSUE TITLE
Admin Design - Sub-Admin List (Desktop View)

### ISSUE THREAD

**Issue by nhorah** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#282]
- Design the desktop view for the sub-admin list.
- The screen should consists of the following:
      - the list of the sub-admins - their names, avatars, email addresses, phone numbers and date each user registered.
      - a more option button that would allow the admin view the profile of each sub-admin.
      - a back button that directs the admin back to the user-group screen
      - a button that directs the admin to create a new sub-admin
      - pagination - for easy navigation across pages
- Ensure you use the colors, typography, icons and side navigation on the style guide to ensure consistency.

**Comment by DeAbby** [comment]
hello @nhorah  Please assign me to this project

**Comment by nhorah** [comment]
Hi @DeAbby this is a design issue and someone had worked on it
So we're just creating issues for them now
Sorry about that
