### ISSUE TITLE
Admin Design - Suspended Accounts List (Mobile View)

### ISSUE THREAD

**Issue by De-mi-de** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#287]
- Design the mobile view for the suspended accounts list.
- The screen should consists of the following:
      - the list of the  suspended accounts - their names, avatars and email addresses.
      - a more option button that would allow the admin view the profile and/or unsuspend each suspended account.
      - a back button that directs the admin back to the user-group screen.
      - pagination - for easy navigation across pages.
- Ensure you use the colors, typography, icons and side navigation on the style guide to ensure consistency.

**Comment by DeAbby** [comment]
Hello @De-mi-de may i please be assigned this issue
