### ISSUE TITLE
Add and setup React Router to handle routing for the application

### ISSUE THREAD

**Issue by EmmanuelObi** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#29]
I'd like to setup react-router for the application, it'll serve very well in handling routing for the app.

**Comment by ingressive4good** [comment]
@EmmanuelObi are you working on this because you didn't assign it to yourself

**Comment by EmmanuelObi** [comment]
Sorry about that. Yes I am.

**Comment by ingressive4good** [comment]
What is the status of this @EmmanuelObi

**Comment by EmmanuelObi** [comment]
It has been merged into its branch. I'm about to reconcile it with the develop branch now.
