### ISSUE TITLE
Authentication: Create Account-UI

### ISSUE THREAD

**Issue by ingressive4good** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#3]
- Develop the create account UI appropriately
- Ensure they are responsive and follow the responsive design on the figma
- Implement images properly
- Follow the color guide and the appropriate colors

**Comment by Funsho-ops** [comment]
Hello, I would like to also work on the Create Account UI, can you please assign me?

**Comment by dprincecoder** [comment]
@Mudi-Igbinoba are you working on this?

**Comment by Mudi-Igbinoba** [comment]
> @Mudi-Igbinoba are you working on this?

Yes @dprincecoder I'll make my pull request before the end of today
