### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by thisletterk** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#30]
I'd like to begin with the header/navigation bar

**Comment by darshikaguptaa** [comment]
Hey, 
I am interested in working on this.
Please assign this issue to me.

**Comment by thisletterk** [comment]
@darshikaguptaa , I was also hoping to get assigned this issue also ☺️

**Comment by Onyelaudochukwuka** [comment]
I think this falls #2 for the landing page navbar 
#16  for the user dashboard
You can comment there so you can be assigned this
