### ISSUE TITLE
Admin Design - Delete Account Pop Up (Desktop View)

### ISSUE THREAD

**Issue by nhorah** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#307]
- Design the desktop view of the delete account pop up.
- The screen should display the following details:
      - a write up that confirms the action
      - a "yes, proceed" button
      - a "no, cancel action" button
- Design a second pop up screen that confirms that the deletion process is successful.
- Ensure you use the colors, typography, icons and side navigation on the style guide to ensure consistency

**Comment by zainbinfurqan** [comment]
HI @nhorah  can i work on it please?
