### ISSUE TITLE
Admin Design - Suspend Account Pop Up (Desktop View)

### ISSUE THREAD

**Issue by De-mi-de** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#310]
- Design the desktop view of the suspend account pop up.
- The screen should display the following details:
      - a write up that confirms the action
      - a "yes, proceed" button
      - a "no, cancel action" button
- Design a second pop up screen that confirms that the suspension process is successful.
- Ensure you use the colors, typography, icons and side navigation on the style guide to ensure consistency

**Comment by zainbinfurqan** [comment]
Hi @De-mi-de  can i work on it please, also can you give some more details like do you want Figma design or codebase design
