### ISSUE TITLE
Admin Design - Improved UX writing on Authentication Screen (Reset Password)

### ISSUE THREAD

**Issue by De-mi-de** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#357]
- Improve UX writing on the reset password screens.
- The improvement should be done on all screens (desktop, tablet and mobile)
- Ensure you use the colors and typography on the style guide to ensure consistency

**Comment by zaahmed-nisum-com** [comment]
@De-mi-de  Can i work on it please.
