### ISSUE TITLE
Admin Design - Improved UX writing on User Profile Screen

### ISSUE THREAD

**Issue by De-mi-de** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#364]
- Improve UX writing on the user profile screens.
- The improvement should be done on all screens (desktop, tablet and mobile)
- Ensure you use the colors and typography on the style guide to ensure consistency

**Comment by cmarchena** [comment]
Hi @De-mi-de, improvements should be done on the Figma document, in the code or both?
Kind regards
