### ISSUE TITLE
Admin Design - Improved UX writing on Delete Product Flow Screens

### ISSUE THREAD

**Issue by nhorah** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#366]
- Improve UX writing on the "delete product" flow screens.
- The improvement should be done on all screens (desktop, tablet and mobile)
- Ensure you use the colors and typography on the style guide to ensure consistency

**Comment by dud3c** [comment]
Hello, I would like to give this one a go. Can I be assigned?
