### ISSUE TITLE
UI: Help and Support Page

### ISSUE THREAD

**Issue by Enx-dev** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#38]
Building out the help and Support page

**Comment by msboffl** [comment]
Hi, @Enx-dev, Can you please assign this to me, i will work

**Comment by ingressive4good** [comment]
@msboffl What is the status of this, you haven't sent a pull request yet

**Comment by msboffl** [comment]
Don't assign to anyone, I'm working on it

**Comment by ingressive4good** [comment]
Alright, looking forward to your pull request
