### ISSUE TITLE
Set Up CI/CD

### ISSUE THREAD

**Issue by Onyelaudochukwuka** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#39]
setting up CI/CD will make the project easier to review.
as all changes made will be reflected making it easier for maintainers to notice errors as the frontend requires a visual representation.

**Comment by maziigwe** [comment]
Can I use netlify this?

**Comment by Onyelaudochukwuka** [comment]
Yes you can

**Comment by ingressive4good** [comment]
Please what is the status on this, no pull request yet @maziigwe @Onyelaudochukwuka

**Comment by ingressive4good** [comment]
I have seen the request from netlify and i have accepted

**Comment by ingressive4good** [comment]
@Onyelaudochukwuka send me a message on telegram please

**Comment by Onyelaudochukwuka** [comment]
OK Sir

**Comment by Onyelaudochukwuka** [comment]
My messages aren't going through saying something about not having your contact stored.
My username is FUMUDUKUS

**Comment by Onyelaudochukwuka** [comment]
so I'll be closing it

**Comment by ingressive4good** [comment]
Alright, Thats fine

**Comment by MarsIncarnate** [comment]
Hello. Since this issue is closed I suppose the continuous integration and deployment has been set up, could you post the link so developers can also view the progress and the application behaviour in a production environment.
