### ISSUE TITLE
Admin Design - Adjustment of search icon

### ISSUE THREAD

**Issue by nhorah** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#394]
- Adjust the search icons based on the feedback received during the general review meeting.
- Corrections should be made on all screens (desktop, tablet and mobile views must be corrected).
- Ensure you use the colors, typography and icons on the style guide to ensure consistency.

**Comment by MarsIncarnate** [comment]
When was the general review meeting? I must've missed it.

**Comment by nhorah** [comment]
it was a review meeting with the designers
