### ISSUE TITLE
Faulty links on dashboard page report

### ISSUE THREAD

**Issue by MarsIncarnate** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#423]
### What is the current behavior?

Multiple links to external pages on dashboard page don't lead anywhere

### What is the expected behavior?

The messages page, product, wishlist, help and support links are expected to lead the user to the respective pages.

**Comment by nirajpdn** [comment]
@MarsIncarnate, I want to work on this.

**Comment by MarsIncarnate** [comment]
@nirajpdn I've worked on this already but you can fix the messages page and logout behavior. You can also help make all the different pages uniform.

**Comment by nirajpdn** [comment]
> @nirajpdn I've worked on this already but you can fix the messages page and logout behavior. You can also help make all the different pages uniform.

Sure @MarsIncarnate , push all the updates and assign this to me as well.
