### ISSUE TITLE
Code of conduct for contributors

### ISSUE THREAD

**Issue by codewithmide** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#49]
A code of conduct is vital for the success of every community. I have listed few rules which can be applied by every contributor on behalf of the community in my PR

**Comment by adeola-dev** [comment]
I would like to work on this documentation. Kindly assign it to me.

**Comment by codewithmide** [comment]
@adeola-dev it can't be assigned to you. If you have fixes just raised an issue, fork the repo, make the changes and create a pull request. You should see [contributing.md](https://github.com/Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022/blob/develop/CONTRIBUTING.md) for more information.

**Comment by adeola-dev** [comment]
Alright, thank you.
