### ISSUE TITLE
Authentication: KYC-FORM-UI

### ISSUE THREAD

**Issue by dabsclement** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#6]
- Develop the KYC PAGE UI appropriately
- Ensure they are responsive and follow the responsive design on the Figma
- Implement images properly
- Follow the colour guide and the appropriate colours

**Comment by Gbemi-m** [comment]
I'd love to be assigned to work on this issue

**Comment by shamim-12** [comment]
Please assign me to work on this issue

**Comment by msboffl** [comment]
Can you please assign this to me i will work on it

**Comment by dprincecoder** [comment]
I am working on this now

**Comment by dprincecoder** [comment]
issue fixed
