### ISSUE TITLE
Authentication: Phone-number-verification-UI

### ISSUE THREAD

**Issue by dabsclement** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#7]
- Develop PHONE NUMBER VERIFICATION page UI appropriately
- Ensure they are responsive and follow the responsive design on the Figma
- Implement images properly
- Follow the colour guide and the appropriate colours

**Comment by mnamesujit** [comment]
Hey i want to work with you can you assign me this issue
