### ISSUE TITLE
[BUG] report - Fix routing issue

### ISSUE THREAD

**Issue by t-bello7** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#72]
### Prior Issues

Are there any existing issues or PRs that relate to this problem? If so, link them here.
#2 #65 #3 #5 #6 #7 #8

### What is the current behavior?
The pages are not linked to the correct routes

**Comment by mminuwaali** [comment]
I think we should have a separation of concern regarding the routing between pages, and I have an idea on how to make things easier as the routing kind of confuse me and took me some time to figure out something about this project, what do you think

**Comment by t-bello7** [comment]
What do you suggest ?

**Comment by mminuwaali** [comment]
I suggest we should have a route file that only specifies the routes and their components, and a file that only loops through the array of routes and displaying them, that way we can have room for improvements if time comes and it will be easy to update just like the screenshot below

![Screenshot from 2022-10-08 17-02-39](https://user-images.githubusercontent.com/62774609/194716628-03c55903-69eb-4b83-8835-b1b5b304e2a6.png)
