### ISSUE TITLE
Develop the Forgot Password page

### ISSUE THREAD

**Issue by Basit46** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#74]
Title
-----

Development of the Forgot Password page

**Comment by t-bello7** [comment]
This a duplicate of #10

**Comment by Basit46** [comment]
God Abeg 
You can Close it bro.

**Comment by t-bello7** [comment]
Try and look at the issues created first. If no one has been assigned then you can assign and work on it. Have assigned #66 to you though. I closed #65 cause someone said he has finished working on it on the channel.
