### ISSUE TITLE
Authentication: Login-UI

### ISSUE THREAD

**Issue by dabsclement** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#9]
Develop Login page UI appropriately
Ensure they are responsive and follow the responsive design on the Figma
Implement images properly
Follow the colour guide and the appropriate colours

**Comment by SahilMahadwar** [comment]
Hi i would like to work on this can you share the figma file and color guidelines?

**Comment by dabsclement** [comment]
Hello @SahilMahadwar thank you for your interest in closing this issue. 

We are currently setting up the issues and contributions will be open by 3rd of October 

Thank you

**Comment by Eunit99** [comment]
I will like to work on this.

**Comment by omotayobolu** [comment]
I'd be working on this.

**Comment by omotayobolu** [comment]
I don't understand, but nobody assigned it to his/her self before me.

**Comment by scarnation** [comment]
@omotayobolu I probably misread it as a design issue because of its UI flag but just noticed the milestone for front-end

**Comment by omotayobolu** [comment]
okay no problem

**Comment by omotayobolu** [comment]
Done
