### ISSUE TITLE
[CONTRIBUTING GUIDELINE FIX] Request to add the Style guide and Project structure documentation

### ISSUE THREAD

**Issue by t-bello7** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#96]
## What docs page needs to be fixed?
Request to add the Style guide and Project structure documentation
- **STYLE GUIDE**:
This section would communicate clearly the style guide followed in the project. Also providing resources for developers to learn about technologies they are not familiar with but used in the project. I suggest the documentation can be written based on this article https://andela.com/insights/structuring-your-react-application-atomic-design-principles/
- **PROJECT STRUCTURE**
This section would define the file structure of the application. The routes and redux configuration. The tools used and conventions followed would be properly discussed here.

## What is the problem?
The chaos of developers just adding any code as long as it can be deployed on netlify is causing redundant code and no clear site of the project structure. Having the style guide and project structure documentation would give both developers and maintainers a reference when reviewing code.
## What should be changed to fix the problem?
The entire file structure and routing follow the atomic design principle. The CSS design framework to be approved should only be tailwind CSS.

**Comment by t-bello7** [comment]
Hi, @Gbemi-m can join you in working on this?

**Comment by Osilaja78** [comment]
Hi @t-bello7 of I get you clearly, this issue is seeking a fix to the contributing guidelines and should include style guide (from figma), and a proper explanation of the atomic principle (for those who doesn't understand what it is) to enable proper check and to ensure every contributors follow the same folder structure. I would like to know if I'm correct cause I would like to take it up.

**Comment by t-bello7** [comment]
Yes @Osilaja78. I'm currently refactoring the codebase to follow the proposed file structure while adding tests to the project.

**Comment by Osilaja78** [comment]
Alright @t-bello7 on it already.

**Comment by Osilaja78** [comment]
@t-bello7 I think creating a style_guide.md file will be better for adding the style guide to not make the contributing.md look too cumbersome. I can do that if you think it's okay.

**Comment by t-bello7** [comment]
Yeah. Creating a style guide is better.

**Comment by Osilaja78** [comment]
Alright, will make a pull request later today.
